### ISSUE TITLE
不正确的fork？

### ISSUE THREAD

**Issue by horrordor** [lxjfzlxj/rustlings#1]
本项目似乎是[rustlings](https://github.com/rust-lang/rustlings)的一个fork，但是作者似乎并没有正确的和原始项目关联，亦为声明原始作者。考虑到这么做似乎也未必违反mit开源协议，但还是请作者做出说明。

**Comment by lxjfzlxj** [comment]
已经在 README 中添加说明

**Comment by horrordor** [comment]
Great, thanks.

________________________________

已经在 README 中添加说明

―
